version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .docker-env

volumes:
  node_modules:
